### ISSUE TITLE
CI failing without even running

### ISSUE THREAD

**Issue by chrisjsewell** [eth-cscs/pyfirecrest#45]
Heya, for some reason the github actions CI has started failing before it even runs 🤔 

For example, in #44, you can see I just made a minimal change to the readme, and it still fails 😬

**Comment by ekouts** [comment]
Hey, there is some issue with the billing, I am seeing this error: 🤔
"The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings."
Let me check if this on my account and happens for other repos or the org..

**Comment by chrisjsewell** [comment]
Ughh! I would of thought, because it's open source it's free 🫠

**Comment by ekouts** [comment]
It has to do with the organization, I don't have any problem with my repos but my PR to pyfirecrest also failed. I will try to contact someone and see if we can fix this 🤦 Spending limits also seem to reset every month so hopefully Wednesday at worst it will be working again 😆

**Comment by ekouts** [comment]
So this was a bug on Github apparently and indeed the actions are free for public repositories :) A colleague contacted them and they fixed it, so I will re-run the tests in your PRs
